### ISSUE TITLE
Get-CommandDetail doesn't work: -Name arguments aren't recognized

### ISSUE THREAD

**Issue by mklement0** [EliziumNet/Loopz#142]
Just installed v3.0.0 from the PS Gallery, but `Get-CommandDetail` appears to be broken (tried on macOS and Windows 10):

```powershell
PS> Get-CommandDetail Get-Date
Get-Command: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

PS> Get-CommandDetail -Name Get-Date
Get-Command: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

**Comment by plastikfan** [comment]
Arg ok. But Get-CommandDetail is not supported (was just left in for reference). Please just use the commands documented. Actually, I probably should not have left Get-CommandDetail in the module, slipped my mind. I meant to remove it before the release. Get-CommandDetail is replaced by Show-ParameterSetInfo.

**Comment by plastikfan** [comment]
PS: You are invoking Get-CommandDetail incorrectly! What you meant to do was:

> gcm Get-Date | Get-CommandDetail

or

> 'Get-Date' | Get-CommandDetail

but as I say, please dont use 'Get-CommandDetail', its not documented or supported.

**Comment by mklement0** [comment]
I see. I didn't notice the name change when you advertised the functionality  [here](https://github.com/PowerShell/PowerShell/issues/8692#issuecomment-820686439).

> You are invoking Get-CommandDetail incorrectly!

The same problem applies to `Show-ParameterSetInfo`:

* The syntax diagram also suggests that  a `-Name` argument is required (and invocation without arguments prompts for a name)
* The error message provides no clue as to why passing an actual name doesn't work.

* `Get-Help Show-ParameterSetInfo -Examples` provides no examples.

If you need to retain this invocation style for _technical_ reasons, I suggest at least providing a meaningful error message that guides the user.

For the user it would be much easier if you allowed, say, `Show-ParameterSetInfo Get-Date` and performed `Get-Command` on it behind the scenes (ideally also with alias resolution).

**Comment by plastikfan** [comment]
Ok, @mklement0, I put a lot of effort into documenting the functionality, hoping that users would read it. I may have neglected the -examples options (that just passed me by, my bad). But please read the documentation, I sweated blood and tears to try and get this right. I take your point about the invocation, but the correct way to invoke is all documented.

If you dont want to use get-command, then just pipe the name of the command in quotes, and Show-CommandDetail does the Get-Command internally.

You are right about the syntax diagram and the -Name prop. This is a bit misleading and needs to be improved. I will have a think about this and mitigate.

**Comment by plastikfan** [comment]
PS, thanks for the feedback

**Comment by mklement0** [comment]
First, to be clear: what the cmdlet does is great, and I commend you for making it freely available.

I had a genuine interest in trying it out, and these are the problems I ran into - given that I knew about the command's purpose and that I had consulted the syntax diagram, it didn't even occur to me that I was doing something wrong and therefore needed to read the documentation.

Note that the help page for the specific command also provides no clues: https://github.com/EliziumNet/Loopz/blob/master/Elizium.Loopz/docs/Show-ParameterSetInfo.md

I suppose that this is where the examples would go, but note that local help didn't show up for me at all.

To adapt the function to my needs, I've just added a `shipsx`  function to my `$PROFILE`:
* It accepts a (single) command name by argument.
* It resolves an alias to its underlying command.

Therefore, I can invoke it as follows, for instance:

```powershell
# Same as: `Get-Command Show-ParameterSetInfo | ships`
PS> shipsx ships  # Command name by argument, automatic resolution of alias to underlying command 

----> Parameter Set Info [Show-ParameterSetInfo] ...

# ...
```

```powershell
function shipsx {
  <#
    .SYNOPSIS
    Wrapper command for Show-ParameterSetInfo that allows passing commands
    by argument.

    .DESCRIPTION
    NOTE: Requires `Install-Module Elizium.Loopz`.
          See https://github.com/EliziumNet/Loopz  
    #>
  [CmdletBinding(PositionalBinding = $false)]
  param(
    [Parameter(Mandatory, Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
    [ValidateNotNullOrEmpty()]
    $Name, # [object] - accept either a name (string) or a [CommandInfo] instance.
    
    [Parameter(Position = 1)]
    [string[]]
    $Sets,
    
    [object] # Should be: [Scribbler]; type not available.
    $Scribbler,
    
    [string]
    $Title,
    
    [switch]
    $Common,
    
    [switch]
    $Test
  )
    
  # Remove a -Name argument from the pass-through arguments, as we'll be
  # using the pipeline instead.
  $null = $PSBoundParameters.Remove('Name')

  # Input via the pipeline.
  if ($MyInvocation.ExpectingInput) { $Name = @($Input) }
      
  # Resolve aliases to their underlying commands.
  $Name | ForEach-Object {
    $cmd = 
      if ($_ -is [System.Management.Automation.CommandInfo]) { $_ }
      else { Get-Command -ErrorAction SilentlyContinue "$_" }
    if (-not $cmd) { $Error[0] | Write-Error }
    if ($cmd -is [System.Management.Automation.AliasInfo]) { 
      $cmd = $cmd.ResolvedCommand
      if (-not $cmd) { Write-Error "'$_' is an alias, but its target command doesn't exist."; return }
    }
    $cmd # Pass out the resolved [CommandInfo] instance.
  } | Show-ParameterSetInfo @PSBoundParameters

}
```

**Comment by plastikfan** [comment]
I think the misleading part about the Name parameter is due to it being defined as 'ValueFromPipeline' and 'ValueFromPipelineByPropertyName' and the syntax statement doesn't reflect this, which from this example, I now see as an issue. Ideally, the Name parameter in the syntax should be marked in some way indicating that it does not need to be specified explicity and that it should be populated by the pipeline.

**Comment by plastikfan** [comment]
@mklement0, I thank you for your input, it very valuable and you do make a good point which I will action. You shouldnt need to define your own wrapper. I get that you want to invoke a different way, and I don't mind accommodating that request, seems reasonable to me, but as in my last comment, then syntax statement, doesnt reflect piple parameters, which I think is a problem. I will also, add more examples to the powershell help, that was a silly ommission on my part.

**Comment by mklement0** [comment]
Thanks, @plastikfan.

As for the syntax and syntax diagram - these are problems I wish were resolved in PowerShell itself:

* Generally, users should be free to choose between passing a value by pipeline and by argument.

  * Commands that only accept _meaningful_ input via the pipeline typically use `-InputObject` as the parameter, although that is still problematic, because the presence of `-InputObject` in the syntax diagram still suggest that by-argument passing is supported: see https://github.com/PowerShell/PowerShell/issues/4242

* That syntax diagrams currently provide no indication as to which parameters are pipeline-binding is a general problem: https://github.com/PowerShell/PowerShell/issues/4135

There's a couple more issues: https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+syntax+diagram

**Comment by plastikfan** [comment]
Ooh, from that issues you referenced, you clearly have strong views about this sort of thing and have thought about this a lot more than I have.

**Comment by mklement0** [comment]
Yes, I think PowerShell's syntax diagrams are in dire need of improvement.

Your command is a great alternative.

Can I suggest another thing?

It's completely a matter of taste, but I personally wish:

* that the column headers weren't that prominent in terms of coloring.
* that, similarly, the coloring the _common_ parameters were less prominent than that of the _command-specific_ ones.

**Comment by plastikfan** [comment]
Thanks for the complement. The selection of colours is tricky. To some degree, the colouring is outside of the control of the command, because it depends on the colour scheme that has been set up in Windows Terminal (I'm assuming you're using that). So something that looks tame in my set up, might look complete garish in yours. FYI, the colour scheme I use and is reflected in the screen shots in the documention is iterm2's Adventure Time. If you dont mind, could you post a screen shot of your terminal showing the result of *ships*, it is interesting to me to see how it looks on somebody else's setup.

**Comment by mklement0** [comment]
I see, thanks for the background info; yes, the look definitely varies. I've posted screenshots in #146, in the context of seeing misaligned columns.

**Comment by plastikfan** [comment]
Fixed in Release 3.0.1. Commands can now be invoked with -Name parameter and aliases are supported too.

**Comment by mklement0** [comment]
That's great, thank you - installed, and it works as expected.

The following is just a quibble: (Mistaken) invocation _without arguments_ yields "Parameter set cannot be resolved using the specified named parameters." rather than prompting for a `-Name` argument / complaining about the missing `-Name`.

**Comment by plastikfan** [comment]
I'm not sure I can do anything about that. Mandatory parameters are prompted for, when the parameter set can be deduced. If no parameters are supplied, then there is no parameter set in play, which means it can't prompt for the name. I think this issue is a characteristic of the design of parameter sets.

**Comment by mklement0** [comment]
You just need to designate a _default_ parameter set:

```powershell
  [CmdletBinding(DefaultParameterSetName='ByName')]
```
